function plotNCAWeightMatrix(weightmatrix,st)
    figure('Color','white')
    % normalize
    weightmatrix=weightmatrix/max(weightmatrix(:));
    imagesc(weightmatrix)
    cmap = [ones(1,256);linspace(1,0,256);linspace(1,0,256)]';
    colormap(cmap)
    colorbar
    for x = 1:size(weightmatrix,2)
        for y=1:size(weightmatrix,1)
            text(x,y,num2str(weightmatrix(y,x),'%.2f'),'Color',[0,0,0],'HorizontalAlignment','center','FontSize',12);
        end
    end
    if st==0
        ylabels = {
            'mean-f1',...
            'variance-f2',...
            'range-f3',...
            'skewness-f4',...
            'kurtosis-f5',...
            'waveform len-f6',...
            'WAMP-f7',...
            'FFT mean mag-f8',...
            'FFT mean frq-f9',...
            'FFT B1-f10',...
            'FFT B2-f11',...
            'FFT B3-f12',...
            'FFT B4-f13',...
            'FFT B5-f14',...
            'FWT J0 mean -f15',...
            'FWT J0 var  -f16',...
            'FWT J0 range-f17',...
            'FWT J0 skew -f18',...
            'FWT J0 kurt -f19',... 
            'FWT J1 mean -f20',...
            'FWT J1 var  -f21',...
            'FWT J1 range-f22',...
            'FWT J1 skew -f23',...
            'FWT J1 kurt -f24',...
            'FWT J2 mean -f25',...
            'FWT J2 var  -f26',...
            'FWT J2 range-f27',...
            'FWT J2 skew -f28',...
            'FWT J2 kurt -f29',...
            'FWT J3 mean -f30',...
            'FWT J3 var  -f31',...
            'FWT J3 range-f32',...
            'FWT J3 skew -f33',...
            'FWT J3 kurt -f34',...
            'FWT J4 mean -f35',...
            'FWT J4 var  -f36',...
            'FWT J4 range-f37',...
            'FWT J4 skew -f38',...
            'FWT J4 kurt -f39',...
            'FWT J5 mean -f40',...
            'FWT J5 var  -f41',...
            'FWT J5 range-f42',...
            'FWT J5 skew -f43',...
            'FWT J5 kurt -f44'...
        };
        set(gca,'YTick', 1:size(weightmatrix,1), 'YtickLabel', ylabels,'FontSize', 10,...
            'FontName','Courier New');
        set(gca,'XTick', 1:size(weightmatrix,2))

        ax = gca;
        ax.XLabel.String = 'Frame Descriptor';
        ax.XLabel.FontSize = 12;
        ax.XLabel.FontName = 'Times';
        ax.YLabel.String = 'Temporal Feature';
        ax.YLabel.FontName = 'Times';
        ax.YLabel.FontSize = 12;
    elseif st == 1
                ylabels = {
            'f1',...
            'f2',...
            'f3',...
            'f4',...
            'f5',...
            'f6',...
            'f7',...
            'f8',...
            'f9',...
            'f10'
            
        };
        set(gca,'YTick', 1:size(weightmatrix,1), 'YtickLabel', ylabels,'FontSize', 10,...
            'FontName','Courier New');
        set(gca,'XTick', 1:size(weightmatrix,2))

        ax = gca;
        ax.XLabel.String = 'Key Frame';
        ax.XLabel.FontSize = 12;
        ax.XLabel.FontName = 'Times';
        ax.YLabel.String = 'Spacial Feature';
        ax.YLabel.FontName = 'Times';
        ax.YLabel.FontSize = 12;
    end
end